name: Failing Demo - Unapproved Action Usage

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4   # Allowed (GitHub-owned)

      - name: Use a third-party action (should be blocked)
        uses: JamesIves/github-pages-deploy-action@v4   # ❌ Not GitHub-owned

      - name: Final step
        run: echo "This workflow intentionally violates Allowed Actions Policy."
