name: Validate Allowed Actions

on:
  workflow_dispatch:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure only approved actions are used
        run: |
          echo "Scanning for unauthorized actions..."
          if grep -R "uses:" .github/workflows/*.yml | grep -v "actions/"; then
            echo "❌ Unauthorized third-party actions detected!"
            exit 1
          fi
          echo "✅ All actions comply with policy."
